# Project information
site_name: 'Race On'
site_description: 'Self-Driving Car Competition'
site_author: 'The Race On Organizing Team'


# Repository
repo_name: 'Race On Tutorials'
repo_url: 'https://github.com/race-on/workshops/'
edit_uri: ''


# Copyright
copyright: 'Copyright &copy; 2020 The Race On organizing team'


# Folders configuration for GitHub Pages
docs_dir: 'source'
site_dir: 'docs'


# Configuration
theme:
  logo: 'images/logo.png'
  favicon: 'images/favicon.png'
  custom_dir: 'theme'
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'


# Customization
extra:
  manifest: 'manifest.webmanifest'

extra_css:
  - 'stylesheets/extra.css'
  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/arithmatex.js


# Google Analytics
google_analytics:
  - 'UA-155985310-1'
  - 'auto'

plugins:
  - search
  - awesome-pages


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed
  - footnotes
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - meta
  - toc:
      permalink: true
  
